CREATE TABLE EMPLOYEE_TABLE (

  ID bigserial NOT NULL unique,

  BIRTH_YEAR VARCHAR(4),
  BIRTH_MONTH VARCHAR(2),
  BIRTH_DAY VARCHAR(2),

  SCHOOL_TYPE INTEGER,
  SCHOOL_NAME VARCHAR(128),
  FACULTY VARCHAR(128),
  DEPARTMEMT VARCHAR(128),

  GRADUATE BIT default '0',
  GRADUATE_YEAR VARCHAR(4),
  GRADUATE_MONTH VARCHAR(2),

  SELF_PR VARCHAR(2048),

  PRIMARY KEY (ID)

);