CREATE TABLE TALK_REQUEST_TABLE (

	ID bigserial NOT NULL,
	REQUESTED_USER_ID bigserial NOT NULL,
	REQUEST_DATE TIMESTAMP DEFAULT now() NOT NULL,
	MATCHING Bit(1) NOT NULL  default '0',
	MATCHING_DATE TIMESTAMP DEFAULT now(),

	PRIMARY KEY (ID, REQUESTED_USER_ID)
);