CREATE TABLE USER_TABLE (

	ID bigserial NOT NULL unique,
	PASSWORD VARCHAR(64) NOT NULL,
	USER_TYPE INTEGER,
	ACTIVATION BIT default'0',
	MAIL_VERIFIED BIT default'0',
	SHOW_FLAG BIT default'0',

	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64) NOT NULL,
	GENDER INTEGER,
	TELL VARCHAR(11) NOT NULL,
	MAIL VARCHAR(512) NOT NULL unique,
	REGISTRATION_AREA VARCHAR(256) NOT NULL,
	REGISTRATION_DATE TIMESTAMP DEFAULT now() NOT NULL,

	PRIMARY KEY (ID)
);