CREATE TABLE USER_TABLE (

	ID bigserial NOT NULL unique,
	PASSWORD VARCHAR(64) NOT NULL,
	USER_TYPE INTEGER,
	ACTIVATION BIT,
	MAIL_VERIFIED BIT,

	FIRST_NAME VARCHAR(64) NOT NULL,
	LAST_NAME VARCHAR(64) NOT NULL,
	GENDER INTEGER,
	TELL VARCHAR(11) NOT NULL,
	MAIL VARCHAR(512) NOT NULL unique,
	REGISTRATION_DATE TIMESTAMP DEFAULT now() NOT NULL,

	PRIMARY KEY (ID)

);



CREATE FUNCTION b2n(bool) RETURNS Bit AS
'select
  case
    when $1 IS TRUE
    then CAST(1 AS Bit)
    else CAST(0 AS Bit)
    end;'
LANGUAGE SQL;



create cast(bool as Bit) WITH FUNCTION b2n(bool) AS ASSIGNMENT;